version: '3.8'

volumes:
  postgres_data:

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    env_file:
      - ./.env

  web:
    image: dasemenov/foodgram-project:latest
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.5-alpine
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/code/static
      - ./media:/code/media
    ports:
      - "80:80"
    depends_on:
      - web