# Generated by Django 2.2 on 2021-03-16 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0004_auto_20210312_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='favorite_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_recipes', through='recipes.Favorite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='purchase_by',
            field=models.ManyToManyField(blank=True, related_name='shop_list', through='recipes.Purchase', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='recipes.Tag'),
        ),
        migrations.AddConstraint(
            model_name='number',
            constraint=models.UniqueConstraint(fields=('ingredient', 'amount', 'recipe'), name='ingredient_unique'),
        ),
    ]
