# Generated by Django 2.2 on 2021-03-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20210318_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='recipes', through='recipes.Number', to='recipes.Ingredient', verbose_name='Ингредиенты'),
        ),
    ]
