# Generated by Django 2.2 on 2021-03-19 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20210318_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='recipes.Ingredient', verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='number',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='recipes.Recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание рецепта'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название рецепта'),
        ),
    ]
