# Generated by Django 2.2 on 2021-03-20 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20210319_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='purchase_by',
            field=models.ManyToManyField(blank=True, related_name='listed_recipes', through='recipes.Purchase', to=settings.AUTH_USER_MODEL),
        ),
    ]
