# Generated by Django 2.2 on 2021-03-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20210320_2057'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='number',
            name='ingredient_unique',
        ),
        migrations.AddConstraint(
            model_name='number',
            constraint=models.UniqueConstraint(fields=('ingredient', 'recipe'), name='ingredient_unique'),
        ),
    ]
