# Generated by Django 2.2 on 2021-03-23 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_auto_20210323_1838'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='number',
            name='ingredient_unique',
        ),
    ]
